// source: proto/StockPoint.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.database.service.StockPoint', null, global);
goog.exportSymbol('proto.database.service.StockPoints', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.database.service.StockPoint = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.database.service.StockPoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.database.service.StockPoint.displayName = 'proto.database.service.StockPoint';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.database.service.StockPoints = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.database.service.StockPoints.repeatedFields_, null);
};
goog.inherits(proto.database.service.StockPoints, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.database.service.StockPoints.displayName = 'proto.database.service.StockPoints';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.database.service.StockPoint.prototype.toObject = function (opt_includeInstance) {
    return proto.database.service.StockPoint.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.database.service.StockPoint} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.database.service.StockPoint.toObject = function (includeInstance, msg) {
    var f, obj = {
      stockIndex: jspb.Message.getFieldWithDefault(msg, 1, 0),
      stockPrice: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.database.service.StockPoint}
 */
proto.database.service.StockPoint.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.database.service.StockPoint;
  return proto.database.service.StockPoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.database.service.StockPoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.database.service.StockPoint}
 */
proto.database.service.StockPoint.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setStockIndex(value);
        break;
      case 2:
        var value = /** @type {number} */ (reader.readDouble());
        msg.setStockPrice(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.database.service.StockPoint.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.database.service.StockPoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.database.service.StockPoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.database.service.StockPoint.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getStockIndex();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getStockPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
};


/**
 * optional int32 stock_index = 1;
 * @return {number}
 */
proto.database.service.StockPoint.prototype.getStockIndex = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.database.service.StockPoint.prototype.setStockIndex = function (value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional double stock_price = 2;
 * @return {number}
 */
proto.database.service.StockPoint.prototype.getStockPrice = function () {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.database.service.StockPoint.prototype.setStockPrice = function (value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.database.service.StockPoints.repeatedFields_ = [1];


if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.database.service.StockPoints.prototype.toObject = function (opt_includeInstance) {
    return proto.database.service.StockPoints.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.database.service.StockPoints} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.database.service.StockPoints.toObject = function (includeInstance, msg) {
    var f, obj = {
      stockPointsList: jspb.Message.toObjectList(msg.getStockPointsList(),
        proto.database.service.StockPoint.toObject, includeInstance)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.database.service.StockPoints}
 */
proto.database.service.StockPoints.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.database.service.StockPoints;
  return proto.database.service.StockPoints.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.database.service.StockPoints} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.database.service.StockPoints}
 */
proto.database.service.StockPoints.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto.database.service.StockPoint;
        reader.readMessage(value, proto.database.service.StockPoint.deserializeBinaryFromReader);
        msg.addStockPoints(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.database.service.StockPoints.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.database.service.StockPoints.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.database.service.StockPoints} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.database.service.StockPoints.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getStockPointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.database.service.StockPoint.serializeBinaryToWriter
    );
  }
};


/**
 * repeated StockPoint stock_points = 1;
 * @return {!Array<!proto.database.service.StockPoint>}
 */
proto.database.service.StockPoints.prototype.getStockPointsList = function () {
  return /** @type{!Array<!proto.database.service.StockPoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.database.service.StockPoint, 1));
};


/** @param {!Array<!proto.database.service.StockPoint>} value */
proto.database.service.StockPoints.prototype.setStockPointsList = function (value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.database.service.StockPoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.database.service.StockPoint}
 */
proto.database.service.StockPoints.prototype.addStockPoints = function (opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.database.service.StockPoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.database.service.StockPoints.prototype.clearStockPointsList = function () {
  this.setStockPointsList([]);
};


goog.object.extend(exports, proto.database.service);
