// source: proto/StockDailySummary.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var proto_Stock_pb = require('../proto/Stock_pb.js');
goog.object.extend(proto, proto_Stock_pb);
goog.exportSymbol('proto.database.service.StockDailySummary', null, global);
goog.exportSymbol('proto.database.service.StockHistDailySummaries', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.database.service.StockDailySummary = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.database.service.StockDailySummary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.database.service.StockDailySummary.displayName = 'proto.database.service.StockDailySummary';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.database.service.StockHistDailySummaries = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.database.service.StockHistDailySummaries.repeatedFields_, null);
};
goog.inherits(proto.database.service.StockHistDailySummaries, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.database.service.StockHistDailySummaries.displayName = 'proto.database.service.StockHistDailySummaries';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.database.service.StockDailySummary.prototype.toObject = function (opt_includeInstance) {
    return proto.database.service.StockDailySummary.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.database.service.StockDailySummary} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.database.service.StockDailySummary.toObject = function (includeInstance, msg) {
    var f, obj = {
      date: jspb.Message.getFieldWithDefault(msg, 1, 0),
      open: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
      close: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
      high: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
      low: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
      lastDayClose: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
      volume: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
      turnover: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.database.service.StockDailySummary}
 */
proto.database.service.StockDailySummary.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.database.service.StockDailySummary;
  return proto.database.service.StockDailySummary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.database.service.StockDailySummary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.database.service.StockDailySummary}
 */
proto.database.service.StockDailySummary.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setDate(value);
        break;
      case 2:
        var value = /** @type {number} */ (reader.readDouble());
        msg.setOpen(value);
        break;
      case 3:
        var value = /** @type {number} */ (reader.readDouble());
        msg.setClose(value);
        break;
      case 4:
        var value = /** @type {number} */ (reader.readDouble());
        msg.setHigh(value);
        break;
      case 5:
        var value = /** @type {number} */ (reader.readDouble());
        msg.setLow(value);
        break;
      case 6:
        var value = /** @type {number} */ (reader.readDouble());
        msg.setLastDayClose(value);
        break;
      case 7:
        var value = /** @type {number} */ (reader.readDouble());
        msg.setVolume(value);
        break;
      case 8:
        var value = /** @type {number} */ (reader.readDouble());
        msg.setTurnover(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.database.service.StockDailySummary.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.database.service.StockDailySummary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.database.service.StockDailySummary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.database.service.StockDailySummary.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getDate();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getOpen();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getClose();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getHigh();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getLow();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getLastDayClose();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getVolume();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getTurnover();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
};


/**
 * optional int64 date = 1;
 * @return {number}
 */
proto.database.service.StockDailySummary.prototype.getDate = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.database.service.StockDailySummary.prototype.setDate = function (value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional double open = 2;
 * @return {number}
 */
proto.database.service.StockDailySummary.prototype.getOpen = function () {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.database.service.StockDailySummary.prototype.setOpen = function (value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double close = 3;
 * @return {number}
 */
proto.database.service.StockDailySummary.prototype.getClose = function () {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.database.service.StockDailySummary.prototype.setClose = function (value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double high = 4;
 * @return {number}
 */
proto.database.service.StockDailySummary.prototype.getHigh = function () {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.database.service.StockDailySummary.prototype.setHigh = function (value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double low = 5;
 * @return {number}
 */
proto.database.service.StockDailySummary.prototype.getLow = function () {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.database.service.StockDailySummary.prototype.setLow = function (value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double last_day_close = 6;
 * @return {number}
 */
proto.database.service.StockDailySummary.prototype.getLastDayClose = function () {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/** @param {number} value */
proto.database.service.StockDailySummary.prototype.setLastDayClose = function (value) {
  jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double volume = 7;
 * @return {number}
 */
proto.database.service.StockDailySummary.prototype.getVolume = function () {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/** @param {number} value */
proto.database.service.StockDailySummary.prototype.setVolume = function (value) {
  jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional double turnover = 8;
 * @return {number}
 */
proto.database.service.StockDailySummary.prototype.getTurnover = function () {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/** @param {number} value */
proto.database.service.StockDailySummary.prototype.setTurnover = function (value) {
  jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.database.service.StockHistDailySummaries.repeatedFields_ = [2];


if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.database.service.StockHistDailySummaries.prototype.toObject = function (opt_includeInstance) {
    return proto.database.service.StockHistDailySummaries.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.database.service.StockHistDailySummaries} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.database.service.StockHistDailySummaries.toObject = function (includeInstance, msg) {
    var f, obj = {
      stock: (f = msg.getStock()) && proto_Stock_pb.Stock.toObject(includeInstance, f),
      dailySummaryList: jspb.Message.toObjectList(msg.getDailySummaryList(),
        proto.database.service.StockDailySummary.toObject, includeInstance)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.database.service.StockHistDailySummaries}
 */
proto.database.service.StockHistDailySummaries.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.database.service.StockHistDailySummaries;
  return proto.database.service.StockHistDailySummaries.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.database.service.StockHistDailySummaries} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.database.service.StockHistDailySummaries}
 */
proto.database.service.StockHistDailySummaries.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto_Stock_pb.Stock;
        reader.readMessage(value, proto_Stock_pb.Stock.deserializeBinaryFromReader);
        msg.setStock(value);
        break;
      case 2:
        var value = new proto.database.service.StockDailySummary;
        reader.readMessage(value, proto.database.service.StockDailySummary.deserializeBinaryFromReader);
        msg.addDailySummary(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.database.service.StockHistDailySummaries.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.database.service.StockHistDailySummaries.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.database.service.StockHistDailySummaries} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.database.service.StockHistDailySummaries.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getStock();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto_Stock_pb.Stock.serializeBinaryToWriter
    );
  }
  f = message.getDailySummaryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.database.service.StockDailySummary.serializeBinaryToWriter
    );
  }
};


/**
 * optional Stock stock = 1;
 * @return {?proto.database.service.Stock}
 */
proto.database.service.StockHistDailySummaries.prototype.getStock = function () {
  return /** @type{?proto.database.service.Stock} */ (
    jspb.Message.getWrapperField(this, proto_Stock_pb.Stock, 1));
};


/** @param {?proto.database.service.Stock|undefined} value */
proto.database.service.StockHistDailySummaries.prototype.setStock = function (value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.database.service.StockHistDailySummaries.prototype.clearStock = function () {
  this.setStock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.database.service.StockHistDailySummaries.prototype.hasStock = function () {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated StockDailySummary daily_summary = 2;
 * @return {!Array<!proto.database.service.StockDailySummary>}
 */
proto.database.service.StockHistDailySummaries.prototype.getDailySummaryList = function () {
  return /** @type{!Array<!proto.database.service.StockDailySummary>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.database.service.StockDailySummary, 2));
};


/** @param {!Array<!proto.database.service.StockDailySummary>} value */
proto.database.service.StockHistDailySummaries.prototype.setDailySummaryList = function (value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.database.service.StockDailySummary=} opt_value
 * @param {number=} opt_index
 * @return {!proto.database.service.StockDailySummary}
 */
proto.database.service.StockHistDailySummaries.prototype.addDailySummary = function (opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.database.service.StockDailySummary, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.database.service.StockHistDailySummaries.prototype.clearDailySummaryList = function () {
  this.setDailySummaryList([]);
};


goog.object.extend(exports, proto.database.service);
