# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/StockDailySummary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import Stock_pb2 as proto_dot_Stock__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/StockDailySummary.proto',
  package='database.service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dproto/StockDailySummary.proto\x12\x10\x64\x61tabase.service\x1a\x11proto/Stock.proto\"\x93\x01\n\x11StockDailySummary\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\r\n\x05\x63lose\x18\x03 \x01(\x01\x12\x0c\n\x04high\x18\x04 \x01(\x01\x12\x0b\n\x03low\x18\x05 \x01(\x01\x12\x16\n\x0elast_day_close\x18\x06 \x01(\x01\x12\x0e\n\x06volume\x18\x07 \x01(\x01\x12\x10\n\x08turnover\x18\x08 \x01(\x01\"}\n\x17StockHistDailySummaries\x12&\n\x05stock\x18\x01 \x01(\x0b\x32\x17.database.service.Stock\x12:\n\rdaily_summary\x18\x02 \x03(\x0b\x32#.database.service.StockDailySummaryb\x06proto3')
  ,
  dependencies=[proto_dot_Stock__pb2.DESCRIPTOR,])




_STOCKDAILYSUMMARY = _descriptor.Descriptor(
  name='StockDailySummary',
  full_name='database.service.StockDailySummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='database.service.StockDailySummary.date', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open', full_name='database.service.StockDailySummary.open', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close', full_name='database.service.StockDailySummary.close', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high', full_name='database.service.StockDailySummary.high', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low', full_name='database.service.StockDailySummary.low', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_day_close', full_name='database.service.StockDailySummary.last_day_close', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='database.service.StockDailySummary.volume', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turnover', full_name='database.service.StockDailySummary.turnover', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=218,
)


_STOCKHISTDAILYSUMMARIES = _descriptor.Descriptor(
  name='StockHistDailySummaries',
  full_name='database.service.StockHistDailySummaries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock', full_name='database.service.StockHistDailySummaries.stock', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='daily_summary', full_name='database.service.StockHistDailySummaries.daily_summary', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=345,
)

_STOCKHISTDAILYSUMMARIES.fields_by_name['stock'].message_type = proto_dot_Stock__pb2._STOCK
_STOCKHISTDAILYSUMMARIES.fields_by_name['daily_summary'].message_type = _STOCKDAILYSUMMARY
DESCRIPTOR.message_types_by_name['StockDailySummary'] = _STOCKDAILYSUMMARY
DESCRIPTOR.message_types_by_name['StockHistDailySummaries'] = _STOCKHISTDAILYSUMMARIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockDailySummary = _reflection.GeneratedProtocolMessageType('StockDailySummary', (_message.Message,), {
  'DESCRIPTOR' : _STOCKDAILYSUMMARY,
  '__module__' : 'proto.StockDailySummary_pb2'
  # @@protoc_insertion_point(class_scope:database.service.StockDailySummary)
  })
_sym_db.RegisterMessage(StockDailySummary)

StockHistDailySummaries = _reflection.GeneratedProtocolMessageType('StockHistDailySummaries', (_message.Message,), {
  'DESCRIPTOR' : _STOCKHISTDAILYSUMMARIES,
  '__module__' : 'proto.StockDailySummary_pb2'
  # @@protoc_insertion_point(class_scope:database.service.StockHistDailySummaries)
  })
_sym_db.RegisterMessage(StockHistDailySummaries)


# @@protoc_insertion_point(module_scope)
