# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/StockPoint.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='proto/StockPoint.proto',
    package='database.service',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\x16proto/StockPoint.proto\x12\x10\x64\x61tabase.service\"6\n\nStockPoint\x12\x13\n\x0bstock_index\x18\x01 \x01(\x05\x12\x13\n\x0bstock_price\x18\x02 \x01(\x01\"A\n\x0bStockPoints\x12\x32\n\x0cstock_points\x18\x01 \x03(\x0b\x32\x1c.database.service.StockPointb\x06proto3')
)

_STOCKPOINT = _descriptor.Descriptor(
    name='StockPoint',
    full_name='database.service.StockPoint',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='stock_index', full_name='database.service.StockPoint.stock_index', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='stock_price', full_name='database.service.StockPoint.stock_price', index=1,
            number=2, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=44,
    serialized_end=98,
)

_STOCKPOINTS = _descriptor.Descriptor(
    name='StockPoints',
    full_name='database.service.StockPoints',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='stock_points', full_name='database.service.StockPoints.stock_points', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=100,
    serialized_end=165,
)

_STOCKPOINTS.fields_by_name['stock_points'].message_type = _STOCKPOINT
DESCRIPTOR.message_types_by_name['StockPoint'] = _STOCKPOINT
DESCRIPTOR.message_types_by_name['StockPoints'] = _STOCKPOINTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockPoint = _reflection.GeneratedProtocolMessageType('StockPoint', (_message.Message,), {
    'DESCRIPTOR': _STOCKPOINT,
    '__module__': 'proto.StockPoint_pb2'
    # @@protoc_insertion_point(class_scope:database.service.StockPoint)
})
_sym_db.RegisterMessage(StockPoint)

StockPoints = _reflection.GeneratedProtocolMessageType('StockPoints', (_message.Message,), {
    'DESCRIPTOR': _STOCKPOINTS,
    '__module__': 'proto.StockPoint_pb2'
    # @@protoc_insertion_point(class_scope:database.service.StockPoints)
})
_sym_db.RegisterMessage(StockPoints)

# @@protoc_insertion_point(module_scope)
